<?php
$tableProducts = [
    'prod0001' => ['Mug Wild Code School Logo', '19.90', 'White ceramic mug with the red Wild Code School\'s logo. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mug1.jpg','1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K64989' ] ,
    'prod0002' => ['Mug Wild Code School Logo Deer', '19.90', 'White ceramic mug with the Deer Wild Code School\'s logo. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mug2.png', '1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K64991'],
    'prod0003' => ['Mug Dinosaur Google', '19.90', 'White ceramic mug with the famous Google Dinosaur. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/front.png', '1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K66321'] ,
    'prod0004' => ['Mug Geek Joke', '19.90', 'White ceramic mug designed with joke about geek. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/muggeek.jpeg', '1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K66334'] ,
    'prod0005' => ['Mug Star Wars R2D2', '19.90', 'White ceramic mug with black handle, designed with the famous character from Star Wars : R2D2. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mug-geek-parodie-star-wars-r2-je-suis-to.jpg', '1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K66347'] ,
    'prod0006' => ['Mug Design won\'t save the world', '19.90', 'Black ceramic mug about design. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mugdesign01.png', '1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K66354'] ,
    'prod0007' => ['Mug Aestetic Silver', '19.90', 'White ceramic mug with silver pattern. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mugdesign02.jpg', '1,1 lbs', 'H 9,5 x W 8', 'Ceramic', 'K66366'] ,
    'prod0008' => ['Mug Aestetic Gold', '19.90', 'White ceramic mug with gold pattern. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mugdesign03.jpg', '1,1 lbs', 'H 9,5 x W 8', 'Ceramic', 'K66373'] ,
    'prod0009' => ['Mug Pacman Black', '19.90', 'Black ceramic mug with a printed design from the famous game Pacman. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mugpacman.jpg', '1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K66380'] ,
    'prod0010' => ['Mug Algorithm Of Success Black', '19.90', 'White ceramic mug with a coding printed design. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mugprog.jpg', '1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K66399' ] ,
    'prod0011' => ['Mug Pusheen', '19.90', 'White ceramic mug with a printed design from the famous cat Pusheen. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mugpusheen.jpg', '1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K6640'] ,
    'prod0012' => ['Mug Retro Gaming Gameboy', '19.90', 'White ceramic mug with a printed design from the famous retro gaming Nintendo. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/mugretrogeek.jpg', '1,1 lbs', 'H 12,5 x W 8', 'Ceramic', 'K66415'] ,
    'prod0013' => ['Ecocup Logo Deer Wild Code School', '5.90', 'White ecocup made with recycled plastic and printed with the Wild Code School\'s deer logo. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/gob1.png', '0,350 lbs', 'H 33,3 x W 7,5', 'Recycled plastic', 'K75328'] ,
    'prod0014' => ['Ecocup Logo Wild Code School', '5.90', 'White ecocup made with recycled plastic and printed with the Wild Code School\'s red logo. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/gob2.png', '0,350 lbs', 'H 33,3 x W 7,5', 'Recycled plastic', 'K75331'] ,
    'prod0015' => ['Ecocup Assassin\'s Creed White', '5.90', 'White ecocup made with recycled plastic and printed with the Assassin\'s Creed logo. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/gobas.jpg', '0,350 lbs', 'H 33,3 x W 7,5', 'Recycled plastic', 'K75341' ] ,
    'prod0016' => ['Ecocup Bethesda Vault Boy','5.90', 'Transparent ecocup made with recycled plastic and printed with Vault Boy from Bethesda. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/gobfallout.jpg', '0,350 lbs', 'H 33,3 x W 7,5', 'Recycled plastic', 'K75357'] ,
    'prod0017' => ['Ecocup Gaming Link', '5.90','Blue ecocup made with recycled plastic and printed with Link from the famous game Zelda. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/goblink.jpg', '0,350 lbs', 'H 33,3 x W 7,5', 'Recycled plastic', 'K75369'] ,
    'prod0018' => ['Ecocup Daryl The Walking Dead', '5.90', 'Black and red ecocup made with recycled plastic and printed with Daryl from The Walking Dead. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/gobwd.jpg', '0,350 lbs', 'H 33,3 x W 7,5', 'Recycled plastic', 'K75375'] ,
    'prod0019' => ['Bowl Logo Wild Code School Deer', '10.90', 'White ceramic bowl with the Deer Wild Code School\'s logo. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/bol1.png', '1,3 lbs', 'H 13 x W 13', 'Ceramic', 'K86232'] ,
    'prod0020' => ['Bowl Logo Wild Code School', '10.90', 'White ceramic bowl with the red Wild Code School\'s logo. Delivred in a protective packaging. Compatible with dishwasher and microwaves.', 'assets/img/kitchen/bol2.png', '1,3 lbs', 'H 13 x W 13', 'Ceramic', 'K86243']
];

?>