INSERT INTO `wildbazar`.`goodies_product`
(title, short_title, price, summary, picture, char_feature, char_category, char_subcategory, char_size, char_color, char_reference)
VALUES
('Badge Wild Code School - Deer',
 'Badge WCS - Deer',
 19.90,
 'Official 2017 Wild Code School badge. Deer picture.',
 'badges/badgewild1.png',
 'Badges',
 'Others',
 'Wild Code School',
 2.1,
 'Multicolor',
 'B65233'
 ),
('Keyring Sauron Eye',
 'Keyring Sauron Eye',
 0.90,
 'Elven Runes Script One Ring to Rule Them All The Eye of Sauron Bronze',
 'keyring/sauron.jpg',
 'Keyring',
 'Movies',
 'The Lord of the Rings',
 1.2,
 'Gold',
 'K11284'
),
('Sticker Bleach - 5 stickers',
 'Sticker Bleach',
 2.90,
 'Sticker Bleach - Collection of 5 stickers.',
 'stickers/bleach.jpg',
'Sticker',
 'Mangas',
 'Bleach',
  7.4,
 'Multicolor',
 'S38987'
),
('Sticker Spok - Star Trek',
 'Sticker Spok',
 3.90,
 'Sticker Spok - Star Trek.',
 'stickers/spok.png',
 'Sticker',
 'Movies',
 'Star Trek',
2.7,
 'Multicolor',
 'S34474'
),
('Badge Cartman - Hall monitor',
 'Badge Cartman - Hall',
 9.90,
 'Badge Cartman - Hall monitor. The famous bad kid!',
 'badges/badgecartman.jpg',
 'Badges',
 'Cartoons',
 'South Park',
2.4,
 'Multicolor',
 'B66688'
),
('Sticker Windows 95',
 'Sticker Windows 95',
 9.90,
 'Sticker Windows 95 - The BEST operating system Ever.',
 'stickers/windows.png',
 'Sticker',
 'Others',
 'Informatics',
3.6,
 'Multicolor',
 'S78474'
),
('Badge StromTrooper - StarBuck\'s',
 'Badge StormBuck\'s',
 15.90,
 'Badge StromTrooper - Starbucks styling.',
 'badges/badgetroopbucks.jpeg',
 'Badges',
 'Movies',
 'Star wars',
 1.9,
 'Blank & green',
 'B98934'
),
('Badge Star Wars - Logo',
 'Badge Star Wars Logo',
 15.90,
 'Badge Star Wars - Official logo',
 'badges/starwarslogo.jpg',
 'Badges',
 'Movies',
 'Star wars',
 2.1,
 'Black',
 'B98934'
),
('Badge Lord of the Rings',
 'Badge Lord of the Rings',
 0.01,
 'What else?',
 'badges/lordofring.jpg',
 'Badges',
 'Movies',
 'The Lord of the Rings',
 1.8,
 'Green',
 'B74234'
),
('Lighter Star wars - Special Edition',
 'Lighter Star Wars',
 39.90,
 'Lighter Star wars - Special Edition. Dark Vador styling.',
 'lighters/lighterdarkvador.jpg',
 'Lighter',
 'Movies',
 'Star wars',
 6.4,
 'Metal',
 'L15234'
),
('Lighter Batman - Official logo',
 'Lighter Batman logo',
 44.90,
 'Lighter Batman - Official logo. Flip Top Lighter Refillable',
 'lighters/batman.jpg',
 'Lighter',
 'Comics',
 'Batman',
5.8,
 'Black',
 'L78284'
),
('Sticker Shrek',
 'Sticker Shrek',
 7.90,
 'Sticker Shrek "Ggggrrrreeeeeuuuurrrkkkk',
 'stickers/shrek.png',
 'Sticker',
 'Movies',
 'Shrek',
1.4,
 'Multicolor',
 'S32137'
),
('Lighter Hellfest',
 'Lighter Hellfest',
66.66,
 'Lighter Hellfest - Special Edition. Flip Top Lighter',
 'lighters/hellfest.jpg',
 'Lighter',
 'Music',
 'Events',
6.6,
 'Metal',
 'L79984'
),
('Badge Airbourne - No Guts No Glory',
 'Badge Airbourne',
9.90,
 'Airbourne - Best Hard rock ever button',
 'badges/musicairbourne.jpg',
 'Badges',
 'Music',
 'Metal',
2.1,
 'Black',
 'B74234'
),
('Keyring Thor Hammer',
 'Keyring Thor Hammer',
 12.90,
 'Vintage Keyring Thor Hammer - Avengers.',
 'keyring/thor.png',
 'Keyring',
 'Comics',
 'Thor',
1.2,
 'Gold',
 'K97884'
),
('Sticker Luigi',
 'Sticker Luigi',
 5.90,
 'Sticker Luigi. Mario\'s Brother! Goooaaallll !!!!',
 'stickers/luigi.png',
 'Sticker',
 'Games',
 'Mario Bros',
 3.1,
 'Green',
 'S21574'
),
('Badge Stan - Fat ass',
 'Badge Stan - Fat ass',
 19.90,
 'Badge Stan "How s it going Fat ass?',
 'badges/badgestan.jpg',
 'Badges',
 'Cartoons',
 'South Park',
2.4,
 'Multicolor',
 'B88954'
),
('Keyring Homer Simpson',
 'Keyring Homer Simpson',
 5.90,
 'Keyring Homer Simpson',
 'keyring/homer.png',
 'Keyring',
 'Cartoons',
 'The Simpsons',
 1.2,
 'Green',
 'K32284'
),
('Badge Suicidal Tendencies - Official logo',
 'Badge Suicidal Tendencies',
19.90,
 'Suicidal Tendencies - Skate Punk Thrash Metal Button Badge',
 'badges/musicsuicidaltendencies.jpg',
 'Badges',
 'Music',
 'Metal',
 2.1,
 'Black',
 'B74894'
),
('Keyring Black Sabbath',
 'Keyring Black Sabbath',
 23.90,
 'Keyring Black Sabbath. Trash metal kings!',
 'keyring/blacksabb.jpg',
 'Badges',
 'Music',
 'Metal',
1.6,
 'Black & Purple',
 'K34874'
);




