/*
-- Query: SELECT * FROM wildbazar.goodies_product
LIMIT 0, 1000

-- Date: 2019-03-28 18:05
*/
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (1,'Badge Wild Code School - Deer','Badge WCS - Deer',19.9,'Official 2017 Wild Code School badge. Deer picture.','badges/badgewild1.png','Badges','Others','Wild Code School',2.1,'Multicolor','B65233');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (2,'Keyring Sauron Eye','Keyring Sauron Eye',0.9,'Elven Runes Script One Ring to Rule Them All The Eye of Sauron Bronze','keyring/sauron.jpg','Keyring','Movies','The Lord of the Rings',1.2,'Gold','K11284');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (3,'Sticker Bleach - 5 stickers','Sticker Bleach',2.9,'Sticker Bleach - Collection of 5 stickers.','stickers/bleach.jpg','Sticker','Mangas','Bleach',7.4,'Multicolor','S38987');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (4,'Sticker Spok - Star Trek','Sticker Spok',3.9,'Sticker Spok - Star Trek.','stickers/spok.png','Sticker','Movies','Star Trek',2.7,'Multicolor','S34474');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (5,'Badge Cartman - Hall monitor','Badge Cartman - Hall',9.9,'Badge Cartman - Hall monitor. The famous bad kid!','badges/badgecartman.jpg','Badges','Cartoons','South Park',2.4,'Multicolor','B66688');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (6,'Sticker Windows 95','Sticker Windows 95',9.9,'Sticker Windows 95 - The BEST operating system Ever.','stickers/windows.png','Sticker','Others','Informatics',3.6,'Multicolor','S78474');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (7,'Badge StromTrooper - StarBuck\'s','Badge StormBuck\'s',15.9,'Badge StromTrooper - Starbucks styling.','badges/badgetroopbucks.jpeg','Badges','Movies','Star wars',1.9,'Blank & green','B98934');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (8,'Badge Star Wars - Logo','Badge Star Wars Logo',15.9,'Badge Star Wars - Official logo','badges/starwarslogo.jpg','Badges','Movies','Star wars',2.1,'Black','B98934');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (9,'Badge Lord of the Rings','Badge Lord of the Rings',0.01,'What else?','badges/lordofring.jpg','Badges','Movies','The Lord of the Rings',1.8,'Green','B74234');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (10,'Lighter Star wars - Special Edition','Lighter Star Wars',39.9,'Lighter Star wars - Special Edition. Dark Vador styling.','lighters/lighterdarkvador.jpg','Lighter','Movies','Star wars',6.4,'Metal','L15234');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (11,'Lighter Batman - Official logo','Lighter Batman logo',44.9,'Lighter Batman - Official logo. Flip Top Lighter Refillable','lighters/batman.jpg','Lighter','Comics','Batman',5.8,'Black','L78284');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (12,'Sticker Shrek','Sticker Shrek',7.9,'Sticker Shrek \"Ggggrrrreeeeeuuuurrrkkkk','stickers/shrek.png','Sticker','Movies','Shrek',1.4,'Multicolor','S32137');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (13,'Lighter Hellfest','Lighter Hellfest',66.66,'Lighter Hellfest - Special Edition. Flip Top Lighter','lighters/hellfest.jpg','Lighter','Music','Events',6.6,'Metal','L79984');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (14,'Badge Airbourne - No Guts No Glory','Badge Airbourne',9.9,'Airbourne - Best Hard rock ever button','badges/musicairbourne.jpg','Badges','Music','Metal',2.1,'Black','B74234');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (15,'Keyring Thor Hammer','Keyring Thor Hammer',12.9,'Vintage Keyring Thor Hammer - Avengers.','keyring/thor.png','Keyring','Comics','Thor',1.2,'Gold','K97884');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (16,'Sticker Luigi','Sticker Luigi',5.9,'Sticker Luigi. Mario\'s Brother! Goooaaallll !!!!','stickers/luigi.png','Sticker','Games','Mario Bros',3.1,'Green','S21574');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (17,'Badge Stan - Fat ass','Badge Stan - Fat ass',19.9,'Badge Stan \"How s it going Fat ass?','badges/badgestan.jpg','Badges','Cartoons','South Park',2.4,'Multicolor','B88954');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (18,'Keyring Homer Simpson','Keyring Homer Simpson',5.9,'Keyring Homer Simpson','keyring/homer.png','Keyring','Cartoons','The Simpsons',1.2,'Green','K32284');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (19,'Badge Suicidal Tendencies - Official logo','Badge Suicidal Tendencies',19.9,'Suicidal Tendencies - Skate Punk Thrash Metal Button Badge','badges/musicsuicidaltendencies.jpg','Badges','Music','Metal',2.1,'Black','B74894');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (20,'Keyring Black Sabbath','Keyring Black Sabbath',23.9,'Keyring Black Sabbath. Trash metal kings!','keyring/blacksabb.jpg','Badges','Music','Metal',1.6,'Black & Purple','K34874');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (23,'Star Wars Storm trooper VII','Star Wars Storm trooper VII',10.9,'Star Wars Storm trooper VII','https://static.fnac-static.com/multimedia/Images/FR/MC/57/8a/2d/36538967/1540-1/tsp20180926091834/Badge-Star-Wars-Episode-VII-Le-reveil-de-la-Force-chaeurs-imperiaux-Power.jpg','Badges','Movies','Star Wars',3.2,'Black','B78445');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (24,'Hulk Keyring','Hulk Keyring',15.2,'A hul keyring!! Be calm!!','https://images-na.ssl-images-amazon.com/images/I/51N66p%2BLMCL._SX425_.jpg','Keyring','Comics','Marvel',2.1,'Green','K58447');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (25,'Batman Keyring','Batman Keyring',23.3,'Batman keyring !!! Be careful Joker!!','https://i.ebayimg.com/images/g/BRsAAOSwZuRZvtpS/s-l640.jpg','Keyring','Comics','DC Comics',2.3,'Black','K59974');
INSERT INTO `goodies_product` (`id`,`title`,`short_title`,`price`,`summary`,`picture`,`char_feature`,`char_category`,`char_subcategory`,`char_size`,`char_color`,`char_reference`) VALUES (26,'Android keyring','Android keyring',12.34,'Android sticker!! Eat the apple!','https://devstickers.com/assets/img/pro/0jwf.png','Sticker','Others','Informatics',5.2,'Green','S54789');
